# Generated by Django 5.2.8 on 2025-11-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('file_url', models.URLField()),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('fetched', models.BooleanField(default=False)),
                ('metadata_status', models.CharField(default='missing', max_length=32)),
                ('last_crawled', models.DateTimeField(blank=True, null=True)),
                ('remote_modified', models.DateTimeField(blank=True, null=True)),
                ('next_crawl', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('title', 'year', 'file_url')},
            },
        ),
    ]
