# Generated by Django 5.2.8 on 2025-12-10 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, unique=True)),
                ('remote_modified', models.DateTimeField(blank=True, null=True)),
                ('last_crawled', models.DateTimeField(auto_now=True)),
                ('movie_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Crawled directories',
            },
        ),
        migrations.CreateModel(
            name='FailedParse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('url', models.URLField(db_index=True, unique=True)),
                ('reason', models.CharField(choices=[('no_media', 'No media files found'), ('parse_error', 'Parse error'), ('timeout', 'Request timeout'), ('network_error', 'Network error'), ('unknown', 'Unknown error')], default='unknown', max_length=32)),
                ('raw_text', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retry_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Failed parses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='directory_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='year_str',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='metadata_status',
            field=models.CharField(db_index=True, default='missing', max_length=32),
        ),
        migrations.AlterField(
            model_name='movie',
            name='popularity',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(db_index=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vote_average',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('overview', models.TextField(blank=True)),
                ('genres', models.JSONField(default=list)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('backdrop_url', models.URLField(blank=True, null=True)),
                ('tagline', models.CharField(blank=True, max_length=512)),
                ('imdb_id', models.CharField(blank=True, max_length=20)),
                ('original_language', models.CharField(blank=True, max_length=10)),
                ('budget', models.BigIntegerField(blank=True, null=True)),
                ('revenue', models.BigIntegerField(blank=True, null=True)),
                ('production_companies', models.JSONField(default=list)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='movies.movie')),
            ],
        ),
    ]
