# Generated by Django 5.2.8 on 2025-12-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_crawleddirectory_failedparse_movie_directory_url_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='file_url',
            field=models.URLField(unique=True),
        ),
    ]
