# Generated by Django 5.2.8 on 2025-12-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_unique_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetail',
            name='cast',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='moviedetail',
            name='director',
            field=models.JSONField(default=dict),
        ),
    ]
